#!/bin/bash

dtiinit=`jq -r '.dtiinit' config.json`

nii=$(jq -r '.files.alignedDwRaw' $dtiinit/dt6.json)
bval=$(jq -r '.files.alignedDwBvals' $dtiinit/dt6.json)
bvec=$(jq -r '.files.alignedDwBvecs' $dtiinit/dt6.json)

ln -sf $dtiinit/$nii dwi.nii.gz
ln -sf $dtiinit/$bval dwi.bvals
ln -sf $dtiinit/$bvec dwi.bvecs

