#!/bin/bash

dtiinit=`jq -r '.dtiinit' config.json`

export nii=$dtiinit/`jq -r '.files.alignedDwRaw' $dtiinit/dt6.json`
export bval=$dtiinit/`jq -r '.files.alignedDwBvals' $dtiinit/dt6.json`
export bvec=$dtiinit/`jq -r '.files.alignedDwBvecs' $dtiinit/dt6.json`

cp -v $nii dwi.nii.gz
cp -v $bval dwi.bvals
cp -v $bvec dwi.bvecs

